### ISSUE TITLE
Problema al iniciar una votación en heroku

### ISSUE THREAD

**Issue by EzequielPJ** [decide-moltres/decide-visualizacion#21]
**Descripción del problema**
Cuando la aplicación con los distintos cambios es desplegada en Heroku gracias a la automatización realizada, nosotrso podemos acceder desde https://decide-moltres-visualizacion.herokuapp.com/admin/ a la creación de distintos tipos de votación para así probar nuestros cambios. Se ha detectado un problema cuando creamos una votación e intentamos iniciarla ya que se nos devuelve un error "ConnectionError" al hacer el método POST. Este error solo lo encontramos en el Heroku de master desplegado ya que en los locales de cada uno de los integrantes del grupo funciona correctamente.

**Pasos seguidos para reproducir el error**
Lo pasos a seguir son:
1. Como la aplicación se encuentra desplegada automáticamente nos dirijimos a https://decide-moltres-visualizacion.herokuapp.com/admin/
2. Si no hay creada ninguna votación debe de crear una. Para ello clicamos en el apatado de "+Add" en la zona de "Votings". Una vez dentro rellenamos los campos de "Name", "Question" y "Auths" con datos de prueba.
3. Volvemos al menu principal y ahora clicamos directamente sobre "Votings".
4. Nos aparecerá una lista donde veremos la votación que hemos creado. Seleccionamos la votación con el cuadrado que aparece a la izquierda del nombre y en el desplegable llamado "Action" elegimos la opción "Start".
5. Finalmente le damos al botón de "Go" y nos aparecerá el error mencionado.

**Resultado deseado tras corregir el error**
Tras corregir el error lo importante es que la aplicación desplegada nos permita iniciar votaciones de prueba para así comprobar que los cambios realizados por el equipo de trabajo funcionan correctamente.

**Pantallazos**

Este es el error que se nos muestra al iniciar la votación 

![Captura](https://user-images.githubusercontent.com/39619194/71513911-ae26a980-289c-11ea-8c42-3af2fdcd8ae8.PNG)

Los primeros logs que nos encontramos del error son los siguientes:

![Captura2](https://user-images.githubusercontent.com/39619194/71513944-d0202c00-289c-11ea-9b1b-262ea9bec8a0.PNG)

**Información de la maquina utilizada:**
 - Sistema operativo: Windows 10 
 - Buscador usado: Opera
 - Versión del sistema operativo: Opera Stable 65.0.3467.78

**Posible solución**
Puede que haya algún archivo en la configuración que no se haya realizado correctamente ya que en local este problema no nos lo encontramos. Estaría bien revisar estos archivos.

**Comment by belengl** [comment]
Este problema ha sido resuelto instalando Pipfile, con el comando pipenv install -r requirements.txt. Esto ha sido posible utilizando la información que hay en: https://stackoverflow.com/questions/49417486/error-when-uploading-to-heroku-git/52228079
