### ISSUE TITLE
Implementación de gráficas

### ISSUE THREAD

**Issue by EzequielPJ** [decide-moltres/decide-visualizacion#3]
**Descripción breve de la tarea a realizar**
Se debe de implementar, con alguna librería adecuada para ello, una serie de gráficas que faciliten la compresión de los resultados de las votaciones.

**Indique, si es posible, con que herramientas se podría realizar esta tarea**
Tkinter puede contener alguna funcionalidad para ello.

**Contenido adicional**
Deben de poder crearse distintos tipos de gráficas (de barras, de líneas...)

**Comment by belengl** [comment]
**Información encontrada al respecto:**
- Librería de JavaScript
[https://www.anychart.com/es/](url)

- Aplicaciones online de creación de gráficas (Posible utilización de APIs)
[https://www.genbeta.com/herramientas/haz-tus-datos-mas-atractivos-con-estas-siete-aplicaciones-online-para-crear-graficas](url)

- Creación de gráficas utilizando Python
[http://research.iac.es/sieinvens/python-course/source/matplotlib.html](url)
